-- AlterTable PlayerRating
ALTER TABLE "PlayerRating" ADD COLUMN "displayWins" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerRating" ADD COLUMN "displayLosses" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerRating" ADD COLUMN "displayQuits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerRating" ADD COLUMN "displayGriefs" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerRating" ADD COLUMN "displayDcs" INTEGER NOT NULL DEFAULT 0;
