#!/usr/bin/env bash
# Cloud Agent install: durable, idempotent setup run after checkout.
# Prepares Node deps, generated Prisma client, a local PostgreSQL 17 cluster,
# the dbzbot database, applied migrations, and a local .env.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# --- Node / npm (align on nvm's Node; ensure npm >= 11 for the openskill git dep) ---
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
# shellcheck disable=SC1091
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" >/dev/null 2>&1 && nvm use default >/dev/null 2>&1 || true

NPM_MAJOR="$(npm -v 2>/dev/null | cut -d. -f1 || echo 0)"
if [ "${NPM_MAJOR:-0}" -lt 11 ]; then
  echo "==> Upgrading npm to 11 (needed to build the openskill git dependency)"
  COREPACK_ENABLE_DOWNLOAD_PROMPT=0 corepack npm@11.6.2 install -g npm@11.6.2
  hash -r
fi
echo "==> node $(node -v) / npm $(npm -v)"

# --- PostgreSQL 17 (matches production; local dev database) ---
PGBIN="/usr/lib/postgresql/17/bin"
if [ ! -x "$PGBIN/postgres" ]; then
  echo "==> Installing PostgreSQL 17 from PGDG"
  sudo install -d /usr/share/postgresql-common/pgdg
  sudo curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
    -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
  . /etc/os-release
  echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main" \
    | sudo tee /etc/apt/sources.list.d/pgdg.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql-17 postgresql-client-17
fi

# --- Initialize a self-contained cluster owned by the current user ---
export PGDATA="$HOME/pgdata"
export PGPORT=5433
if [ ! -f "$PGDATA/PG_VERSION" ]; then
  echo "==> initdb cluster at $PGDATA (port $PGPORT)"
  PWFILE="$(mktemp)"; echo "postgres" >"$PWFILE"
  "$PGBIN/initdb" -D "$PGDATA" -U postgres --auth-local=trust --auth-host=md5 --pwfile="$PWFILE" >/dev/null
  rm -f "$PWFILE"
  {
    echo "port = $PGPORT"
    echo "listen_addresses = '127.0.0.1'"
    echo "unix_socket_directories = '/tmp'"
  } >>"$PGDATA/postgresql.conf"
fi

# --- Bring the cluster up so we can create the DB and apply migrations ---
if ! "$PGBIN/pg_ctl" -D "$PGDATA" status >/dev/null 2>&1; then
  "$PGBIN/pg_ctl" -D "$PGDATA" -l "$HOME/pg.log" -w start
fi
export PGPASSWORD=postgres
if ! "$PGBIN/psql" -h 127.0.0.1 -p "$PGPORT" -U postgres -tc \
  "SELECT 1 FROM pg_database WHERE datname='dbzbot'" | grep -q 1; then
  "$PGBIN/createdb" -h 127.0.0.1 -p "$PGPORT" -U postgres dbzbot
fi

# --- Local .env (placeholders for Discord/Gemini; real Cloud Agent secrets win at runtime) ---
if [ ! -f "$REPO_DIR/.env" ]; then
  echo "==> Writing local .env"
  cat >"$REPO_DIR/.env" <<'ENV'
# Local Cloud Agent development environment (generated by .cursor/install.sh).
# Real values injected as Cloud Agent secrets (process env) take precedence over these.
DISCORD_TOKEN=dev-placeholder-token
CLIENT_ID=0
GEMINI_API_KEY=dev-placeholder-gemini-key
DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5433/dbzbot?schema=public"
DIRECT_URL="postgresql://postgres:postgres@127.0.0.1:5433/dbzbot?schema=public"
NODE_ENV=development
AUTO_DEPLOY_COMMANDS=false
LOG_LEVEL=debug
ENV
fi

# --- Node dependencies + Prisma client + schema ---
echo "==> npm ci"
npm ci
echo "==> prisma generate"
npx prisma generate
echo "==> prisma migrate deploy"
npx prisma migrate deploy

echo "==> install.sh complete"
